version: "3.0"

volumes:
  mongo-sslkeys:
  mongo-data-0:
  mongo-data-1:
  mongo-data-2:
  mongo-data-3:

networks:
  replica-set:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.5.0/24

services:
  mongo-sslkeys:
    image: depop/openssl-bats
    volumes:
      - mongo-sslkeys:/mongo-conf
    command: 'bash -c "openssl rand -base64 741 > /mongo-conf/mongodb-keyfile; chmod 600 /mongo-conf/mongodb-keyfile; chown 999 /mongo-conf/mongodb-keyfile"'

  # Primary
  mongo-primary:
    image: mongo:latest
    volumes:
      - mongo-sslkeys:/opt/keyfile
      - mongo-data-0:/data/db
      - .:/backup
    env_file:
      ./mongod.env
    ports:
      - 27017:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet replica-set'
    depends_on:
        - mongo-sslkeys
    networks:
      replica-set:

  # Slave 1
  mongo-worker-1:
    image: mongo:latest
    volumes:
      - mongo-sslkeys:/opt/keyfile
      - mongo-data-1:/data/db
      - .:/backup
    env_file:
      ./mongod.env
    ports:
      - 27018:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet replica-set'
    depends_on:
        - mongo-sslkeys
    networks:
      replica-set:

  # Slave 2
  mongo-worker-2:
    image: mongo:latest
    volumes:
      - mongo-sslkeys:/opt/keyfile
      - mongo-data-2:/data/db
      - .:/backup
    env_file:
      ./mongod.env
    ports:
      - 27019:27017
    command: 'mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet replica-set'
    depends_on:
        - mongo-sslkeys
    networks:
      replica-set:

  mongosetup:
    image: mongo:latest
    depends_on:
      - mongo-primary
      - mongo-worker-1
      - mongo-worker-2
    restart: "no"
    entrypoint: [ "bash", "sleep 5 && mongo --host mongo:27017 --eval 'rs.initiate()'"]

  api:
    container_name: apiserver
    restart: always
    build: ./API/
    ports:
      - "5000:5000"
    depends_on:
      - mongo-primary
    networks:
      - replica-set

  client:
    container_name: reactclient
    restart: always
    build: ./Frontend_React/
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - replica-set
